export { default as Performance } from './Performance';
export { default as Orders } from './Orders';
export { default as Editor } from './Editor';
export { default as CallHistory } from './CallHistory';
export { default as ColorPicker } from './ColorPicker';
export { default as Calendar } from './Calendar';
export { default as Area } from './Charts/Area';
export { default as Bar } from './Charts/Bar';
export { default as ColorMapping } from './Charts/ColorMapping';
export { default as Financial } from './Charts/Financial';
export { default as Line } from './Charts/Line';
export { default as Pie } from './Charts/Pie';
export { default as Pyramid } from './Charts/Pyramid';
export { default as Stacked } from './Charts/Stacked';
export { default as Profile } from './Profile';
export { default as Home } from './Home';
export { default as Feedback } from './Feedback'; 
export { default as FeedbackNav } from './FeedbackNav'; 

